[workspace]
members = [
    "day1p1", 
    "day1p2",
    "day2",
    "day3",
    "day3p2",
    "day4",
    "day5",
    "day6",
    "day6p2",
    "day7", 
    "day8",
    "day9",
    "day10",
    "day11",
    "day12",
    "day13",
    "day14",
    "day15",
    "day16",
    "day17",
    "day25",
    ]
